/* Insert seed data into the database */
INSERT INTO plant (id, plantname, space, )
VALUES ( 1, 'Asparagus', '12 to 18 inches wide and a full six inches deep. The crowns should be spaced 9 to 12 inches apart.', )
, (2, "Bush Beans", "2 to 4 inches apart in rows at least 18 to 24 inches apart.", )
, (3, "Pole Beans", "4 to 6 inches apart in rows 30 to 36 inches apart.", )
, (4, "Beet", "1/2 inch deep and one inch apart. Allow 12 to 18 inches between rows.", )
, (5, "Broccoli", "18 to 24 inches apart in the row and allow 36 inches between rows.", )
, (6, "Brussels Sprouts", "24 to 36 inches apart in the row, or 24 inches in all directions in beds.", )
, (7, "Cabbage", "12 to 24 inches apart in the row, 12 inches apart in all directions.", )
, (8, "Carrot", "12 to 24 inches apart in the row, 12 inches apart in all directions.", )
, (9, "Cauliflower", "18 to 24 inches apart in the row.", )
, (10, "Celery", "12 to 24 inches apart in the row, 12 inches apart in all directions.", )
, (11, "Chard", "1/2 to 3/4 inches deep (8 to 10 seeds per foot of row) Thin seedlings to 4 to 6 inches apart.", )
, (12, "Collard", "6 inches apart, allow them to grow until they begin to touch, then harvest whole plants to give 18 inches between plants.", )
, (13, "Corn", "Space the kernels 9 to 12 inches apart in the row. Allow 30 to 36 inches between rows", )
, (14, "Cucumber", "one plant every 12 inches in the row.", )
, (15, "Eggplant", "18 to 24 inches apart in the row, allow 30 to 36 inches between rows or space plants 24 inches apart in all directions in raised beds.", )
, (16, "Lettuce", "1/4 to 1/2 inch deep (10 seeds per foot) in single, double or triple rows 12 to 18 inches apart.", )
, (17, "Cantaloupe", "18 to 24 inches apart, space rows at least 5 feet apart.", )
, (18, "Mustard", " 1/3 to 1/2 inch deep and thin seedlings to 3 to 5 inches apart.", )
, (19, "Okra", "1 inch deep, 12 to 24 inches apart.", )
, (20, "Onion", "4 to 5 inches apart in a row, allow 12 to 18 inches between rows or space onions 6 to 8 inches apart in all directions in beds.",)
, (21, "Parsnip", "seed thickly, at least two or three seeds per inch, space rows 18 to 24 inches apart or plants 8 to 10 inches apart in a bed.", )
, (22, "Peas", "1 to 1-1/2 inches deep and one inch apart in single or double rows. Allow 18 to 24 inches between single or pairs of rows. Allow 8 to 10 inches between double rows in pairs.", )
, (23, "Peppers", "18 to 24 inches apart in the row, or 14 to 18 inches apart in all directions in beds.", )
, (24, "Potatoes", "10 to 12 inches apart and cover in a furrow between 1 and 3 inches deep. Space rows 24 to 36 inches apart. The 24 inch spacing is often ideal.", )
, (25, "Pumpkin", "Requires a minimum of 50 to 100 square feet per hill. Plant seeds one inch deep (four or five seeds per hill). Allow 5 to 6 feet between hills, spaced in rows 10 to 15 feet apart.", )
, (26, "Radishes", "18 to 24 inches apart in a row, allow 30 to 36 inches between rows.", )
